name: shelf_web_socket
version: 1.0.1
publish_to: none

description: >-
  A shelf handler that wires up a listener for every connection.
repository: https://github.com/dart-lang/shelf_web_socket

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  shelf:
  # shelf:
  #   path: ../shelf/pkgs/shelf
  stream_channel: ^2.1.0
  web_socket_channel: ^2.0.0

dev_dependencies:
  http: ^0.13.0
  pedantic: ^1.10.0
  # test: ^1.16.0
